################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CXX_SRCS += \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbgwindow.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbitmap.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbutton.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbuttonarray.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccallback.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccheckbox.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccyclebutton.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphbutton.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphsliderhorizontal.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphsliderhorizontalgrip.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cgraphicsport.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cimage.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ckeypad.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clabel.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clatchbutton.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clatchbuttonarray.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistbox.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistboxdataitem.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistdata.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistdataitem.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cmultilinetextbox.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnumericedit.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxfont.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxserver.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxstring.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtimer.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtkwindow.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtoolbar.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxwidget.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxwindow.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cprogressbar.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cradiobutton.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cradiobuttongroup.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/crect.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/crlepalettebitmap.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarhorizontal.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarpanel.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarvertical.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollinglistbox.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollingpanel.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollingtextbox.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderhorizontal.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderhorizontalgrip.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cslidervertical.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderverticalgrip.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstickybutton.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstickybuttonarray.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstringiterator.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctabpanel.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctext.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctextbox.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwidgetcontrol.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwidgeteventhandlerlist.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwindoweventhandlerlist.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowdown.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowleft.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowright.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowup.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_backspace.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_capslock.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxmu.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxoff.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxon.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_control.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_cycle.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_nxlogo.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonmu.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonoff.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonon.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_return.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screendepthdown.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screendepthup.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screenflipdown.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screenflipup.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_shift.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowclose.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowdepthdown.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowdepthup.cxx \
../modules/PX4NuttX/NxWidgets/libnxwidgets/src/singletons.cxx 

OBJS += \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbgwindow.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbitmap.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbutton.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbuttonarray.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccallback.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccheckbox.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccyclebutton.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphbutton.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphsliderhorizontal.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphsliderhorizontalgrip.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cgraphicsport.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cimage.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ckeypad.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clabel.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clatchbutton.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clatchbuttonarray.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistbox.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistboxdataitem.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistdata.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistdataitem.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cmultilinetextbox.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnumericedit.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxfont.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxserver.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxstring.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtimer.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtkwindow.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtoolbar.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxwidget.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxwindow.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cprogressbar.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cradiobutton.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cradiobuttongroup.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/crect.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/crlepalettebitmap.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarhorizontal.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarpanel.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarvertical.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollinglistbox.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollingpanel.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollingtextbox.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderhorizontal.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderhorizontalgrip.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cslidervertical.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderverticalgrip.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstickybutton.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstickybuttonarray.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstringiterator.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctabpanel.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctext.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctextbox.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwidgetcontrol.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwidgeteventhandlerlist.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwindoweventhandlerlist.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowdown.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowleft.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowright.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowup.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_backspace.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_capslock.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxmu.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxoff.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxon.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_control.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_cycle.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_nxlogo.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonmu.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonoff.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonon.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_return.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screendepthdown.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screendepthup.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screenflipdown.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screenflipup.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_shift.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowclose.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowdepthdown.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowdepthup.o \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/singletons.o 

CXX_DEPS += \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbgwindow.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbitmap.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbutton.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cbuttonarray.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccallback.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccheckbox.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ccyclebutton.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphbutton.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphsliderhorizontal.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cglyphsliderhorizontalgrip.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cgraphicsport.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cimage.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ckeypad.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clabel.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clatchbutton.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clatchbuttonarray.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistbox.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistboxdataitem.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistdata.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/clistdataitem.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cmultilinetextbox.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnumericedit.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxfont.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxserver.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxstring.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtimer.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtkwindow.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxtoolbar.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxwidget.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cnxwindow.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cprogressbar.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cradiobutton.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cradiobuttongroup.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/crect.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/crlepalettebitmap.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarhorizontal.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarpanel.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollbarvertical.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollinglistbox.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollingpanel.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cscrollingtextbox.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderhorizontal.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderhorizontalgrip.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cslidervertical.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/csliderverticalgrip.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstickybutton.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstickybuttonarray.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cstringiterator.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctabpanel.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctext.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/ctextbox.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwidgetcontrol.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwidgeteventhandlerlist.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/cwindoweventhandlerlist.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowdown.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowleft.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowright.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_arrowup.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_backspace.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_capslock.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxmu.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxoff.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_checkboxon.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_control.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_cycle.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_nxlogo.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonmu.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonoff.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_radiobuttonon.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_return.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screendepthdown.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screendepthup.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screenflipdown.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_screenflipup.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_shift.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowclose.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowdepthdown.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/glyph_windowdepthup.d \
./modules/PX4NuttX/NxWidgets/libnxwidgets/src/singletons.d 


# Each subdirectory must supply rules for building sources it contributes
modules/PX4NuttX/NxWidgets/libnxwidgets/src/%.o: ../modules/PX4NuttX/NxWidgets/libnxwidgets/src/%.cxx
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	aarch64-linux-gnu-g++ -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


