################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../modules/PX4NuttX/nuttx/libc/math/lib_acos.c \
../modules/PX4NuttX/nuttx/libc/math/lib_acosf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_acosl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_asin.c \
../modules/PX4NuttX/nuttx/libc/math/lib_asinf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_asinl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_atan.c \
../modules/PX4NuttX/nuttx/libc/math/lib_atan2.c \
../modules/PX4NuttX/nuttx/libc/math/lib_atan2f.c \
../modules/PX4NuttX/nuttx/libc/math/lib_atan2l.c \
../modules/PX4NuttX/nuttx/libc/math/lib_atanf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_atanl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_ceil.c \
../modules/PX4NuttX/nuttx/libc/math/lib_ceilf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_ceill.c \
../modules/PX4NuttX/nuttx/libc/math/lib_cos.c \
../modules/PX4NuttX/nuttx/libc/math/lib_cosf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_cosh.c \
../modules/PX4NuttX/nuttx/libc/math/lib_coshf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_coshl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_cosl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_exp.c \
../modules/PX4NuttX/nuttx/libc/math/lib_expf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_expl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_fabs.c \
../modules/PX4NuttX/nuttx/libc/math/lib_fabsf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_fabsl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_floor.c \
../modules/PX4NuttX/nuttx/libc/math/lib_floorf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_floorl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_fmod.c \
../modules/PX4NuttX/nuttx/libc/math/lib_fmodf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_fmodl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_frexp.c \
../modules/PX4NuttX/nuttx/libc/math/lib_frexpf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_frexpl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_ldexp.c \
../modules/PX4NuttX/nuttx/libc/math/lib_ldexpf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_ldexpl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_libexpi.c \
../modules/PX4NuttX/nuttx/libc/math/lib_libsqrtapprox.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log10.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log10f.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log10l.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log2.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log2f.c \
../modules/PX4NuttX/nuttx/libc/math/lib_log2l.c \
../modules/PX4NuttX/nuttx/libc/math/lib_logf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_logl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_modf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_modff.c \
../modules/PX4NuttX/nuttx/libc/math/lib_modfl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_pow.c \
../modules/PX4NuttX/nuttx/libc/math/lib_powf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_powl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_round.c \
../modules/PX4NuttX/nuttx/libc/math/lib_roundf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_roundl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sin.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sinf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sinh.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sinhf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sinhl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sinl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sqrt.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sqrtf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_sqrtl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_tan.c \
../modules/PX4NuttX/nuttx/libc/math/lib_tanf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_tanh.c \
../modules/PX4NuttX/nuttx/libc/math/lib_tanhf.c \
../modules/PX4NuttX/nuttx/libc/math/lib_tanhl.c \
../modules/PX4NuttX/nuttx/libc/math/lib_tanl.c 

OBJS += \
./modules/PX4NuttX/nuttx/libc/math/lib_acos.o \
./modules/PX4NuttX/nuttx/libc/math/lib_acosf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_acosl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_asin.o \
./modules/PX4NuttX/nuttx/libc/math/lib_asinf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_asinl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_atan.o \
./modules/PX4NuttX/nuttx/libc/math/lib_atan2.o \
./modules/PX4NuttX/nuttx/libc/math/lib_atan2f.o \
./modules/PX4NuttX/nuttx/libc/math/lib_atan2l.o \
./modules/PX4NuttX/nuttx/libc/math/lib_atanf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_atanl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_ceil.o \
./modules/PX4NuttX/nuttx/libc/math/lib_ceilf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_ceill.o \
./modules/PX4NuttX/nuttx/libc/math/lib_cos.o \
./modules/PX4NuttX/nuttx/libc/math/lib_cosf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_cosh.o \
./modules/PX4NuttX/nuttx/libc/math/lib_coshf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_coshl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_cosl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_exp.o \
./modules/PX4NuttX/nuttx/libc/math/lib_expf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_expl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_fabs.o \
./modules/PX4NuttX/nuttx/libc/math/lib_fabsf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_fabsl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_floor.o \
./modules/PX4NuttX/nuttx/libc/math/lib_floorf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_floorl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_fmod.o \
./modules/PX4NuttX/nuttx/libc/math/lib_fmodf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_fmodl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_frexp.o \
./modules/PX4NuttX/nuttx/libc/math/lib_frexpf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_frexpl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_ldexp.o \
./modules/PX4NuttX/nuttx/libc/math/lib_ldexpf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_ldexpl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_libexpi.o \
./modules/PX4NuttX/nuttx/libc/math/lib_libsqrtapprox.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log10.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log10f.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log10l.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log2.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log2f.o \
./modules/PX4NuttX/nuttx/libc/math/lib_log2l.o \
./modules/PX4NuttX/nuttx/libc/math/lib_logf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_logl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_modf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_modff.o \
./modules/PX4NuttX/nuttx/libc/math/lib_modfl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_pow.o \
./modules/PX4NuttX/nuttx/libc/math/lib_powf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_powl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_round.o \
./modules/PX4NuttX/nuttx/libc/math/lib_roundf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_roundl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sin.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sinf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sinh.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sinhf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sinhl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sinl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sqrt.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sqrtf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_sqrtl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_tan.o \
./modules/PX4NuttX/nuttx/libc/math/lib_tanf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_tanh.o \
./modules/PX4NuttX/nuttx/libc/math/lib_tanhf.o \
./modules/PX4NuttX/nuttx/libc/math/lib_tanhl.o \
./modules/PX4NuttX/nuttx/libc/math/lib_tanl.o 

C_DEPS += \
./modules/PX4NuttX/nuttx/libc/math/lib_acos.d \
./modules/PX4NuttX/nuttx/libc/math/lib_acosf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_acosl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_asin.d \
./modules/PX4NuttX/nuttx/libc/math/lib_asinf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_asinl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_atan.d \
./modules/PX4NuttX/nuttx/libc/math/lib_atan2.d \
./modules/PX4NuttX/nuttx/libc/math/lib_atan2f.d \
./modules/PX4NuttX/nuttx/libc/math/lib_atan2l.d \
./modules/PX4NuttX/nuttx/libc/math/lib_atanf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_atanl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_ceil.d \
./modules/PX4NuttX/nuttx/libc/math/lib_ceilf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_ceill.d \
./modules/PX4NuttX/nuttx/libc/math/lib_cos.d \
./modules/PX4NuttX/nuttx/libc/math/lib_cosf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_cosh.d \
./modules/PX4NuttX/nuttx/libc/math/lib_coshf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_coshl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_cosl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_exp.d \
./modules/PX4NuttX/nuttx/libc/math/lib_expf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_expl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_fabs.d \
./modules/PX4NuttX/nuttx/libc/math/lib_fabsf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_fabsl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_floor.d \
./modules/PX4NuttX/nuttx/libc/math/lib_floorf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_floorl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_fmod.d \
./modules/PX4NuttX/nuttx/libc/math/lib_fmodf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_fmodl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_frexp.d \
./modules/PX4NuttX/nuttx/libc/math/lib_frexpf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_frexpl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_ldexp.d \
./modules/PX4NuttX/nuttx/libc/math/lib_ldexpf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_ldexpl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_libexpi.d \
./modules/PX4NuttX/nuttx/libc/math/lib_libsqrtapprox.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log10.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log10f.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log10l.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log2.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log2f.d \
./modules/PX4NuttX/nuttx/libc/math/lib_log2l.d \
./modules/PX4NuttX/nuttx/libc/math/lib_logf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_logl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_modf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_modff.d \
./modules/PX4NuttX/nuttx/libc/math/lib_modfl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_pow.d \
./modules/PX4NuttX/nuttx/libc/math/lib_powf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_powl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_round.d \
./modules/PX4NuttX/nuttx/libc/math/lib_roundf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_roundl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sin.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sinf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sinh.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sinhf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sinhl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sinl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sqrt.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sqrtf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_sqrtl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_tan.d \
./modules/PX4NuttX/nuttx/libc/math/lib_tanf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_tanh.d \
./modules/PX4NuttX/nuttx/libc/math/lib_tanhf.d \
./modules/PX4NuttX/nuttx/libc/math/lib_tanhl.d \
./modules/PX4NuttX/nuttx/libc/math/lib_tanl.d 


# Each subdirectory must supply rules for building sources it contributes
modules/PX4NuttX/nuttx/libc/math/%.o: ../modules/PX4NuttX/nuttx/libc/math/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	aarch64-linux-gnu-gcc -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


